version: 2

defaults: &defaults
  image: ubuntu:focal
  environment:
    CI: "true"

workflows:
 version: 2
 build:
   jobs:
     - build
            
 
jobs:
  build:
    <<: *defaults
    steps:
      - run: echo 'Hellow, world'
